// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_orange_eater = "CgkI3IussIgQEAIQBQ"; // <GPGSID>
        public const string achievement_anaconda = "CgkI3IussIgQEAIQDA"; // <GPGSID>
        public const string achievement_luckiest_player = "CgkI3IussIgQEAIQDw"; // <GPGSID>
        public const string achievement_green_eater = "CgkI3IussIgQEAIQBg"; // <GPGSID>
        public const string achievement_cubiline_player = "CgkI3IussIgQEAIQCg"; // <GPGSID>
        public const string achievement_wiseman = "CgkI3IussIgQEAIQEQ"; // <GPGSID>
        public const string achievement_colorfull = "CgkI3IussIgQEAIQEA"; // <GPGSID>
        public const string leaderboard_high_score = "CgkI3IussIgQEAIQAQ"; // <GPGSID>
        public const string achievement_blue_eater = "CgkI3IussIgQEAIQBA"; // <GPGSID>
        public const string achievement_indianapolis_500 = "CgkI3IussIgQEAIQCw"; // <GPGSID>
        public const string leaderboard_longest = "CgkI3IussIgQEAIQAg"; // <GPGSID>
        public const string achievement_big_player = "CgkI3IussIgQEAIQDQ"; // <GPGSID>
        public const string achievement_multiplier_eater = "CgkI3IussIgQEAIQCQ"; // <GPGSID>
        public const string achievement_open_the_box = "CgkI3IussIgQEAIQAw"; // <GPGSID>
        public const string achievement_gray_eater = "CgkI3IussIgQEAIQBw"; // <GPGSID>
        public const string achievement_magnet_eater = "CgkI3IussIgQEAIQCA"; // <GPGSID>
        public const string achievement_lucky_player = "CgkI3IussIgQEAIQDg"; // <GPGSID>
        public const string achievement_strategist_player = "CgkI3IussIgQEAIQFA"; // <GPGSID>
        public const string achievement_logical_player = "CgkI3IussIgQEAIQEw"; // <GPGSID>
        public const string achievement_cubiline_fan = "CgkI3IussIgQEAIQEg"; // <GPGSID>

}

